services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile

networks:
  default:
    name: caddy_net
    external: true
