services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /home/mushy/containers/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host
    networks:
      - caddy
    labels:
      caddy: home.jshen.net
      caddy.reverse_proxy: "{{upstreams 8123}}"

networks:
  caddy:
    external: true
