services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      # - "8090:8090/tcp" # admin panel
      # - "443:443/tcp"
      # - "443:443/udp"
      - "3000:3000/tcp" # initial installation
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - /home/mushy/containers/adguardhome/work:/opt/adguardhome/work
      - /home/mushy/containers/adguardhome/conf:/opt/adguardhome/conf

networks:
  default:
    name: caddy_net
    external: true
